name = "baking-log"
main = "src/index.ts"
compatibility_date = "2025-09-23"

[[d1_databases]]
binding = "DB"
database_name = "baking-log"
database_id = "28b6fe2b-6bdf-4e80-b804-209dd4cc2353"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "baking-log"

[observability]
enabled = false
